// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM9yJ9CO-1c-3sVnJ8nJwG3D0dJNhkEro',
    appId: '1:205786278593:web:b4913e5a11c4a013398240',
    messagingSenderId: '205786278593',
    projectId: 'assetventory-3c93d',
    authDomain: 'assetventory-3c93d.firebaseapp.com',
    storageBucket: 'assetventory-3c93d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBptc7hU7B9avWLckdwlS8OK1AXDgzBU3s',
    appId: '1:205786278593:android:b254cf337fcd0202398240',
    messagingSenderId: '205786278593',
    projectId: 'assetventory-3c93d',
    storageBucket: 'assetventory-3c93d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCISN4yL1oauFqH3EyBSQNnQbvda28QF_g',
    appId: '1:205786278593:ios:5e12821115cf4f41398240',
    messagingSenderId: '205786278593',
    projectId: 'assetventory-3c93d',
    storageBucket: 'assetventory-3c93d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCISN4yL1oauFqH3EyBSQNnQbvda28QF_g',
    appId: '1:205786278593:ios:5e12821115cf4f41398240',
    messagingSenderId: '205786278593',
    projectId: 'assetventory-3c93d',
    storageBucket: 'assetventory-3c93d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM9yJ9CO-1c-3sVnJ8nJwG3D0dJNhkEro',
    appId: '1:205786278593:web:9a5568b00b76068d398240',
    messagingSenderId: '205786278593',
    projectId: 'assetventory-3c93d',
    authDomain: 'assetventory-3c93d.firebaseapp.com',
    storageBucket: 'assetventory-3c93d.firebasestorage.app',
  );
}
